Prod review.js
Team-Stuckyi/TheGreatCatsby-FrontEnd pull request #44
Opened 2022-02-28 03:51 UTC by 0x000613

2022-02-28 04:06 UTC, ByeongminLee requested changes
우선 이 파일은 상품 상세 페이지에 들어가는 리뷰 부분인거 같은데 해당 부분은 review.js 파일에도 사용해야 되서 따로 컴포넌트를 만들기로 했어죠?

공통 컴포넌트로 제작이 되어 있는 리뷰 컴포넌트 부분을 따로 만든 이유가 있을까요?

2022-02-28 04:06 UTC, ByeongminLee commented on src/components/users/ProdReview.js
> +                    <Stars starCount={4} starSize="24px" />
stars에 props 주는 부분 또한 테스트 값이 아니라 props로 받았을때 돌아가게 되어 있어야 되요~

2022-02-28 04:06 UTC, ByeongminLee commented on src/components/users/ProdReview.js
> +import GlobalStyles from 'GlobalStyles';
GlobalStyles는 App.js에 전역적으로 사용하도록 되어 있어서 굳이 파일마다 명시하지 않아도 적용됩니다.

2022-02-28 04:12 UTC, ByeongminLee requested changes
출력화면을 위해서 ajax연동이 따로 들어가 있지만 데이터 연동 부분이 Redux로 값을 따로 빼서 호출해서 만들기로 했기 때문에 Redux로 값을 호출하는 부분을 구현해서 넣어 줘야해요.

각 파트당 미완성 코드는 병합 시키지 않습니다.
사소한 이슈를 고치는 문제는 병합한뒤 수정해도 괜찮을지 몰라도 해당 파일과 같이 꼭 필요한 구현해야 할 부분이 없는 것은 병합하면 안됩니다.

2022-02-28 04:12 UTC, ByeongminLee commented on src/components/common/ReviewList.js
> +                const response = await axios.get('https://tgc.xeros.dev/reviews/look');
주소를 github에 노출시키지 않고 env파일로 숨기기로 했었습니다.

2022-02-28 04:40 UTC, 0x000613 commented on src/components/users/ProdReview.js
> +            {/* 아래 a태그는 추후 Link 태그로 수정해야함 */}
아.. 저부분 수정한다면서 깜빡했네요.. 수정할게요

2022-02-28 04:59 UTC, abcabcp requested changes

2022-02-28 04:59 UTC, abcabcp commented on src/components/common/ReviewList.js
> +                const response = await axios.get('https://tgc.xeros.dev/reviews/look');
1. 서버연동 redux-toolkit
2. 서버주소 -> .env 파일로 처리

2022-02-28 04:59 UTC, abcabcp commented on src/components/users/ProdReview.js
> +import GlobalStyles from 'GlobalStyles';
글로벌 스타일은 이미 전체 페이지와 컴포넌트에 적용된 상태임
return 시 처음 감싸는 태그를 공통 컴포넌트인 common 의 container를 가보면
1200px의 중앙정렬된 div를 만날 수 있음

2022-02-28 04:59 UTC, abcabcp commented on src/components/users/ProdReview.js
> +const ProdReview = ({ starAvg = '4.8', reviewCount = '(1,842)' }) => {
startAvg -> 추후 서버에 있는 stars_avg
reviewCount -> 추후 서버에 있는 review_count로 받아서 쓸것

2022-03-01 10:41 UTC, 0x000613 commented on src/components/users/ProdReview.js
> +import GlobalStyles from 'GlobalStyles';
수정했습니다.

2022-03-01 10:45 UTC, 0x000613 commented on src/components/users/ProdReview.js
> +const ProdReview = ({ starAvg = '4.8', reviewCount = '(1,842)' }) => {
수정했습니다.

2022-03-01 10:48 UTC, 0x000613 commented on src/components/users/ProdReview.js
> +                    <Stars starCount={4} starSize="24px" />
수정했습니다.

2022-03-02 08:54 UTC, closed without merging